[versions]
appcompat = "1.6.1"
constraintlayout = "2.1.4"
desugar_jdk_libs = "2.0.4"
dicioNumbers = "219cd77023368ff3e4c616ba4a338a8462e2f5b6"
dicioSentencesCompiler = "ae228425c4071448ec09c6026b5b3a80e5744818"
dicioSkill = "d442b542c4bcaeaa10e56574334f4e26c520be2e"
exp4j = "0.4.8"
gradle = "8.4.0"
jna = "5.14.0"
jsoup = "1.17.2"
kotest = "5.8.1"
kotlin = "1.9.24"
material = "1.12.0"
picasso = "2.71828"
preferenceKtx = "1.2.1"
unbescape = "1.1.6.RELEASE"
voskAndroid = "0.3.32"

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
dicio-numbers = { module = "com.github.Stypox:dicio-numbers", version.ref = "dicioNumbers" }
dicio-sentences-compiler = { module = "com.github.Stypox:dicio-sentences-compiler", version.ref = "dicioSentencesCompiler" }
dicio-skill = { module = "com.github.Stypox:dicio-skill", version.ref = "dicioSkill" }
exp4j = { module = "net.objecthunter:exp4j", version.ref = "exp4j" }
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
material = { module = "com.google.android.material:material", version.ref = "material" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
unbescape = { module = "org.unbescape:unbescape", version.ref = "unbescape" }
vosk-android = { module = "com.alphacephei:vosk-android", version.ref = "voskAndroid" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "gradle" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
org-jetbrains-kotlin-plugin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
