import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
import java.io.File
import java.io.FileOutputStream
import javax.crypto.Cipher
import javax.crypto.spec.SecretKeySpec

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath(libs.dicio.sentences.compiler.plugin)
    }
}

plugins {
    alias(libs.plugins.com.android.application)
    alias(libs.plugins.org.jetbrains.kotlin.android)
    alias(libs.plugins.org.jetbrains.kotlin.plugin.compose)
    alias(libs.plugins.org.jetbrains.kotlin.plugin.parcelize)
    alias(libs.plugins.org.jetbrains.kotlin.plugin.serialization)
    alias(libs.plugins.com.google.devtools.ksp)
    alias(libs.plugins.com.google.dagger.hilt.android)
    alias(libs.plugins.com.google.protobuf)

    // 使用传统方式应用插件，避免与buildscript冲突
    id("org.stypox.dicio.sentencesCompilerPlugin")
}

// ===== 版本号读取（从VERSION文件）=====
val versionFile = File(rootProject.projectDir, "VERSION")
val finalVersionName: String = run {
    if (versionFile.exists()) {
        try {
            versionFile.readText().trim()
        } catch (e: Exception) {
            println("⚠️  读取VERSION文件失败，使用默认版本号: ${e.message}")
            "3.19.43"
        }
    } else {
        println("⚠️  VERSION文件不存在，使用默认版本号")
        "3.19.43"
    }
}

// Git commit数量（用于versionCode计算）
val gitCommitCount: Int = run {
    try {
        val process = Runtime.getRuntime().exec("git rev-list --count HEAD")
        process.waitFor()
        val result = process.inputStream.bufferedReader().readText().trim()
        if (result.isNotEmpty()) result.toInt() else 0
    } catch (e: Exception) {
        0
    }
}

// 基础版本代码
val baseVersionCode = 16

// 最终版本代码
val finalVersionCode = baseVersionCode + gitCommitCount

android {
    namespace = "com.ai.voice"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.ai.voice"
        minSdk = 26
        targetSdk = 36
        versionCode = finalVersionCode
        versionName = finalVersionName
        testInstrumentationRunner = "com.ai.voice.CustomTestRunner"

        vectorDrawables.useSupportLibrary = true

        // add folders generated by sentencesCompiler task
        sourceSets["main"].java {
            srcDir("build/generated/source/sentences/main")
        }

        ndk {
            // 🆕 只保留ARM架构，移除x86架构以减少APK大小（节省约80MB）
            abiFilters += arrayOf("armeabi-v7a", "arm64-v8a")
        }
    }

    packaging {
        jniLibs {
            // 优先使用SherpaOnnx静态链接版本的libonnxruntime.so
            pickFirsts += "**/libonnxruntime.so"
            pickFirsts += "**/libonnxruntime4j_jni.so"
        }
        resources {
            // 排除重复的资源文件
            excludes += "META-INF/DEPENDENCIES"
            excludes += "META-INF/LICENSE*"
            excludes += "META-INF/NOTICE*"
        }
    }

    // 产品变体：区分普通版本和系统预装版本
    flavorDimensions += "version"
    productFlavors {
        create("normal") {
            dimension = "version"
            // 普通版本：不设置sharedUserId，需要申请权限
            manifestPlaceholders["sharedUserId"] = ""
            buildConfigField("boolean", "IS_SYSTEM_BUILD", "false")
        }
        
        create("system") {
            dimension = "version"
            // 系统预装版本：使用系统UID，不需要申请录音和通知权限
            manifestPlaceholders["sharedUserId"] = "android.uid.system"
            buildConfigField("boolean", "IS_SYSTEM_BUILD", "true")
            // 系统版本的应用名称可以不同（可选）
            resValue("string", "app_name", "VoiceAssistant")
            // 系统版本的release构建使用starry签名
            // 注意：签名配置需要在buildTypes中通过variant配置，这里只是标记
        }
    }

    signingConfigs {
        create("release") {
            storeFile = file("release.keystore")
            storePassword = "android123"
            keyAlias = "release"
            keyPassword = "android123"
        }
        create("510en") {
            storeFile = file("/Users/user/tool/docsample/510-en-key/platform.keystore")
            storePassword = "android"
            keyAlias = "androiddebugkey"
            keyPassword = "android"
        }
        create("pad") {
            storeFile = file("/Users/user/tool/docsample/pad/pad.keystore")
            storePassword = "android"
            keyAlias = "androiddebugkey"
            keyPassword = "android"
        }
        create("starry") {
            storeFile = file("release.keystore")
            storePassword = "android123"
            keyAlias = "release"
            keyPassword = "android123"
        }
    }

    buildTypes {
        debug {
            // 固定包名和应用名，不添加分支后缀
            signingConfig = signingConfigs.getByName("510en")
            resValue("string", "app_name", "VoiceAssistant")
            
            // Debug版本不启用混淆，便于调试
            isMinifyEnabled = false
            isShrinkResources = false
        }
        release {
            // 🔒 启用代码混淆和资源压缩
            isMinifyEnabled = true
            isShrinkResources = true
           
            // ProGuard规则文件
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
            
            // 签名配置：默认使用510en签名（normal版本）
            // system版本的签名在afterEvaluate中通过variant配置
            signingConfig = signingConfigs.getByName("510en")
            
            // 应用名称
            resValue("string", "app_name", "VoiceAssistant")
            
            // 构建配置
            buildConfigField("boolean", "DEBUG_MODE", "false")
            
            // 禁用调试
            isDebuggable = false
            isJniDebuggable = false
            // isRenderscriptDebuggable 已弃用，AGP 9.0将移除
            // isZipAlignEnabled 已弃用，ZIP对齐现在总是启用的
        }
    }
    
    // 在afterEvaluate中为systemRelease变体设置签名
    afterEvaluate {
        // 检查是否有systemRelease相关的任务被请求执行
        val requestedTasks = gradle.startParameter.taskNames
        val isBuildingSystemRelease = requestedTasks.any { 
            it.contains("SystemRelease", ignoreCase = true) || 
            it.contains("systemRelease", ignoreCase = true)
        }
        
        applicationVariants.all {
            val variant = this
            val flavorName = variant.flavorName
            val buildType = variant.buildType.name
            
            // 为system flavor的release构建设置starry签名
            // 只在真正构建systemRelease时才尝试设置签名和显示警告
            if (flavorName == "system" && buildType == "release" && isBuildingSystemRelease) {
                // 注意：signingConfig在较新版本的AGP中是只读的
                // 这里我们通过修改variant的signingConfig属性来实现
                // 如果无法修改，需要在构建时通过gradle参数指定：-PsigningConfig=starry
                try {
                    // 尝试通过反射设置签名配置
                    val signingConfigField = variant.javaClass.getDeclaredField("signingConfig")
                    signingConfigField.isAccessible = true
                    signingConfigField.set(variant, signingConfigs.getByName("starry"))
                } catch (e: Exception) {
                    // 如果反射失败，输出警告信息（只在构建systemRelease时显示）
                    println("⚠️  无法自动设置system版本的签名配置")
                    println("   请使用以下命令构建system版本：")
                    println("   ./gradlew assembleSystemRelease -PsigningConfig=starry")
                }
            }
        }
    }
    
    // ===== 自定义APK文件名格式：VoiceAssistant-版本号-flavor-buildType.apk =====
    // 使用afterEvaluate确保版本信息已计算
    afterEvaluate {
        applicationVariants.all {
            val variant = this
            val buildType = variant.buildType.name
            val flavorName = variant.flavorName
            val versionName = variant.versionName
            
            // 构建APK文件名：VoiceAssistant-版本号-flavor-buildType.apk
            val flavorSuffix = if (flavorName.isNotEmpty() && flavorName != "normal") {
                "-${flavorName.replaceFirstChar { it.uppercase() }}"
            } else {
                ""
            }
            
            val apkFileName = when (buildType) {
                "debug" -> {
                    "VoiceAssistant-${versionName}${flavorSuffix}-Debug.apk"
                }
                "release" -> {
                    "VoiceAssistant-${versionName}${flavorSuffix}-Release.apk"
                }
                else -> {
                    val buildTypeCapitalized = buildType.replaceFirstChar { it.uppercase() }
                    "VoiceAssistant-${versionName}${flavorSuffix}-${buildTypeCapitalized}.apk"
                }
            }
            
            // 使用任务重命名APK文件
            variant.outputs.forEach { output ->
                val packageTask = variant.packageApplicationProvider.get()
                packageTask.doLast {
                    val outputFile = output.outputFile
                    if (outputFile != null && outputFile.exists()) {
                        val newFile = File(outputFile.parent, apkFileName)
                        outputFile.renameTo(newFile)
                        println("✅ APK已重命名为: ${newFile.name}")
                    }
                }
            }
        }
    }

    compileOptions {
        // Flag to enable support for the new language APIs
        isCoreLibraryDesugaringEnabled = true

        sourceCompatibility = JavaVersion.toVersion(libs.versions.java.get())
        targetCompatibility = JavaVersion.toVersion(libs.versions.java.get())
    }

    kotlinOptions {
        jvmTarget = libs.versions.java.get()
    }

    buildFeatures {
        viewBinding = true
        buildConfig = true
        compose = true
    }
    

}

tasks.withType<Test>().configureEach {
    useJUnitPlatform()
}

protobuf {
    protoc {
        artifact = libs.protobuf.protoc.get().toString()
    }
    plugins {
        generateProtoTasks {
            all().forEach {
                it.builtins {
                    create("kotlin") {
                        option("lite")
                    }
                    create("java") {
                        option("lite")
                    }
                }
            }
        }
    }
}

// workaround for https://github.com/google/ksp/issues/1590
// remove when not needed anymore
androidComponents {
    onVariants(selector().all()) { variant ->
        afterEvaluate {
            val capName = variant.name.replaceFirstChar { it.uppercase() }
            tasks.getByName<KotlinCompile>("ksp${capName}Kotlin") {
                setSource(tasks.getByName("generate${capName}Proto").outputs)
            }
        }
    }
}

dependencies {
    // Desugaring
    coreLibraryDesugaring(libs.desugar.jdk.libs)

    // Dicio own libraries
    implementation(libs.dicio.numbers)
    implementation(project(":skill"))

    // Android
    implementation(libs.appcompat)

    // Compose (check out https://developer.android.com/jetpack/compose/bom/bom-mapping)
    implementation(libs.activity.compose)
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.material.icons.extended)
    androidTestImplementation(platform(libs.compose.bom))
    androidTestImplementation(libs.test.android.compose.ui.test.junit4)
    debugImplementation(libs.debug.compose.ui.tooling)
    debugImplementation(libs.debug.compose.ui.test.manifest)
    
    // Lottie for animations
    implementation("com.airbnb.android:lottie-compose:6.1.0")

    // Hilt Dependency Injection
    implementation(libs.hilt.android)
    implementation(libs.hilt.navigation.compose)
    ksp(libs.hilt.android.compiler)
    androidTestImplementation(libs.hilt.android.testing)
    //androidTestAnnotationProcessor(libs.hilt.android.compiler)
    testImplementation(libs.hilt.android.testing)
    testAnnotationProcessor(libs.hilt.android.compiler)

    // Protobuf and Datastore
    implementation(libs.protobuf.kotlin.lite)
    implementation(libs.protobuf.java.lite)
    implementation(libs.datastore)

    // Navigation
    implementation(libs.kotlin.serialization)
    implementation(libs.navigation)

    // Vosk
    implementation(libs.jna) { artifact { type = "aar" } }
    implementation(libs.vosk.android)
    
    // SherpaOnnx AAR (完整版 1.12.14)
    // 包含所有功能：ASR、TTS、VAD等
    implementation(files("libs/sherpa-onnx-1.12.14.aar"))
    
    // Hyundai IT API AAR (设备控制接口)
    implementation(files("libs/hyundaiit-api-v0.1-2025-10-14-16-release.aar"))
    
    // Gson - required by Hyundai IT API
    implementation(libs.gson)
    androidTestImplementation(libs.gson)
    
    // LiteRT / Tensorflow Lite
    implementation(libs.litert)
    
    // ONNX Runtime for HiNudge wake word - 与OpenwakewordforAndroid-main保持一致
    implementation("com.microsoft.onnxruntime:onnxruntime-android:1.19.2")

    // OkHttp
    implementation(platform(libs.okhttp.bom))
    implementation(libs.okhttp)

    // Image loading
    implementation(libs.coil.compose)
    implementation(libs.accompanist.drawablepainter)

    // Permission Flow https://github.com/PatilShreyas/permission-flow-android
    implementation(libs.permission.flow.android)
    implementation(libs.permission.flow.compose)

    // Miscellaneous
    implementation(libs.unbescape)
    implementation(libs.jsoup)

    // Used by skills
    implementation(libs.exp4j)

    // Testing
    testImplementation(libs.kotest.runner.junit5)
    testImplementation(libs.kotest.assertions.core)
    testImplementation(libs.kotest.property)
    androidTestImplementation(libs.test.runner)
    androidTestImplementation(libs.test.rules)
    androidTestImplementation(libs.test.ui.automator)
}

// this is required to avoid NoClassDefFoundError for ActivityInvoker during androidTest
// https://github.com/android/android-test/issues/2247#issuecomment-2194435444
configurations.configureEach {
    resolutionStrategy {
        force(libs.test.core)
        // 强制统一ONNX Runtime版本，避免版本冲突 - 与OpenwakewordforAndroid-main保持一致
        force("com.microsoft.onnxruntime:onnxruntime-android:1.19.2")
        force("ai.onnxruntime:onnxruntime:1.19.2")
    }
}

fun gitBranch(): String {
    return try {
        providers.exec {
            commandLine("git", "rev-parse", "--abbrev-ref", "HEAD")
        }.standardOutput.asText.get().trim()
    } catch (e: Exception) {
        logger.warn("Git isn't installed, using default name for debug app.")
        "debug"
    }
}
