import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
import java.io.File
import java.io.FileOutputStream
import javax.crypto.Cipher
import javax.crypto.spec.SecretKeySpec

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath(libs.dicio.sentences.compiler.plugin)
    }
}

plugins {
    alias(libs.plugins.com.android.application)
    alias(libs.plugins.org.jetbrains.kotlin.android)
    alias(libs.plugins.org.jetbrains.kotlin.plugin.compose)
    alias(libs.plugins.org.jetbrains.kotlin.plugin.parcelize)
    alias(libs.plugins.org.jetbrains.kotlin.plugin.serialization)
    alias(libs.plugins.com.google.devtools.ksp)
    alias(libs.plugins.com.google.dagger.hilt.android)

    // 使用传统方式应用插件，避免与buildscript冲突
    id("org.stypox.dicio.sentencesCompilerPlugin")
}

// ===== Git版本信息获取（移到android块之前）=====
val gitCommitCount: Int = run {
    try {
        val process = Runtime.getRuntime().exec("git rev-list --count HEAD")
        process.waitFor()
        val result = process.inputStream.bufferedReader().readText().trim()
        if (result.isNotEmpty()) result.toInt() else 0
    } catch (e: Exception) {
        0
    }
}

// 基础版本号
val baseVersionMajor = 3
val baseVersionMinor = 3
val baseVersionCode = 16

// 版本号计算规则：修订号0-99循环，每100次commit次版本号+1，次版本号超过99时主版本号+1
// 例如：3.3.0 -> 3.3.99 -> 3.4.0 -> ... -> 3.99.99 -> 4.0.0
val revisionNumber = gitCommitCount % 100  // 修订号：0-99循环
val minorVersionIncrement = (gitCommitCount / 100) % 100  // 次版本号增量：0-99
val majorVersionIncrement = gitCommitCount / 10000  // 主版本号增量
val minorVersion = baseVersionMinor + minorVersionIncrement
val majorVersion = baseVersionMajor + majorVersionIncrement

// 最终版本号
val finalVersionCode = baseVersionCode + gitCommitCount
val finalVersionName = "${majorVersion}.${minorVersion}.${revisionNumber}"

android {
    namespace = "com.ai.voice"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.ai.voice"
        minSdk = 26
        targetSdk = 36
        versionCode = finalVersionCode
        versionName = finalVersionName
        testInstrumentationRunner = "com.ai.voice.CustomTestRunner"

        vectorDrawables.useSupportLibrary = true

        // add folders generated by sentencesCompiler task
        sourceSets["main"].java {
            srcDir("build/generated/source/sentences/main")
        }

        ndk {
            // 🆕 只保留ARM架构，移除x86架构以减少APK大小（节省约80MB）
            abiFilters += arrayOf("armeabi-v7a", "arm64-v8a")
        }
    }

    packaging {
        jniLibs {
            // 优先使用SherpaOnnx静态链接版本的libonnxruntime.so
            pickFirsts += "**/libonnxruntime.so"
            pickFirsts += "**/libonnxruntime4j_jni.so"
        }
        resources {
            // 排除重复的资源文件
            excludes += "META-INF/DEPENDENCIES"
            excludes += "META-INF/LICENSE*"
            excludes += "META-INF/NOTICE*"
        }
    }

    // 已移除渠道与产品变体，统一仅使用 debug/release 构建类型

    signingConfigs {
        create("release") {
            storeFile = file("release.keystore")
            storePassword = "android123"
            keyAlias = "release"
            keyPassword = "android123"
        }
        create("510en") {
            storeFile = file("/Users/user/tool/docsample/510-en-key/platform.keystore")
            storePassword = "android"
            keyAlias = "androiddebugkey"
            keyPassword = "android"
        }
        create("pad") {
            storeFile = file("/Users/user/tool/docsample/pad/pad.keystore")
            storePassword = "android"
            keyAlias = "androiddebugkey"
            keyPassword = "android"
        }


    }

    flavorDimensions += "channel"
    productFlavors {
        create("home") {
            dimension = "channel"
            signingConfig = signingConfigs.getByName("510en")
        }
    }

    buildTypes {
        debug {
            // 固定包名和应用名，不添加分支后缀
            signingConfig = signingConfigs.getByName("510en")
            resValue("string", "app_name", "VoiceAssistant")
            
            // Debug版本不启用混淆，便于调试
            isMinifyEnabled = false
            isShrinkResources = false
        }
        release {
            // 🔒 启用代码混淆和资源压缩
            isMinifyEnabled = true
            isShrinkResources = true
           
            // ProGuard规则文件
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
            
            // 签名配置
            signingConfig = signingConfigs.getByName("510en")
            
            // 应用名称
            resValue("string", "app_name", "VoiceAssistant")
            
            // 构建配置
            buildConfigField("boolean", "DEBUG_MODE", "false")
            
            // 禁用调试
            isDebuggable = false
            isJniDebuggable = false
            // isRenderscriptDebuggable 已弃用，AGP 9.0将移除
            // isZipAlignEnabled 已弃用，ZIP对齐现在总是启用的
        }
    }
    
    // ===== 自定义APK文件名格式：VoiceAssistant-版本号-buildType.apk =====
    // 使用afterEvaluate确保版本信息已计算
    afterEvaluate {
        applicationVariants.all {
            val variant = this
            val buildType = variant.buildType.name
            val versionName = variant.versionName
            
            // 构建APK文件名：VoiceAssistant-版本号-buildType.apk
            val apkFileName = when (buildType) {
                "debug" -> {
                    "VoiceAssistant-${versionName}-Debug.apk"
                }
                "release" -> {
                    "VoiceAssistant-${versionName}-Release.apk"
                }
                else -> {
                    val buildTypeCapitalized = buildType.replaceFirstChar { it.uppercase() }
                    "VoiceAssistant-${versionName}-${buildTypeCapitalized}.apk"
                }
            }
            
            // 使用任务重命名APK文件
            variant.outputs.forEach { output ->
                val packageTask = variant.packageApplicationProvider.get()
                packageTask.doLast {
                    val outputFile = output.outputFile
                    if (outputFile != null && outputFile.exists()) {
                        val newFile = File(outputFile.parent, apkFileName)
                        outputFile.renameTo(newFile)
                        println("✅ APK已重命名为: ${newFile.name}")
                    }
                }
            }
        }
    }

    compileOptions {
        // Flag to enable support for the new language APIs
        isCoreLibraryDesugaringEnabled = true

        sourceCompatibility = JavaVersion.toVersion(libs.versions.java.get())
        targetCompatibility = JavaVersion.toVersion(libs.versions.java.get())
    }

    kotlinOptions {
        jvmTarget = libs.versions.java.get()
    }

    buildFeatures {
        viewBinding = true
        buildConfig = true
        compose = true
    }
    

}

tasks.withType<Test>().configureEach {
    useJUnitPlatform()
}

dependencies {
    // Desugaring
    coreLibraryDesugaring(libs.desugar.jdk.libs)

    // Dicio own libraries
    implementation(libs.dicio.numbers)
    implementation(project(":skill"))

    // Android
    implementation(libs.appcompat)

    // Compose (check out https://developer.android.com/jetpack/compose/bom/bom-mapping)
    implementation(libs.activity.compose)
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.material.icons.extended)
    androidTestImplementation(platform(libs.compose.bom))
    androidTestImplementation(libs.test.android.compose.ui.test.junit4)
    debugImplementation(libs.debug.compose.ui.tooling)
    debugImplementation(libs.debug.compose.ui.test.manifest)
    
    // Lottie for animations
    implementation("com.airbnb.android:lottie-compose:6.1.0")

    // Hilt Dependency Injection
    implementation(libs.hilt.android)
    implementation(libs.hilt.navigation.compose)
    ksp(libs.hilt.android.compiler)
    androidTestImplementation(libs.hilt.android.testing)
    //androidTestAnnotationProcessor(libs.hilt.android.compiler)
    testImplementation(libs.hilt.android.testing)
    testAnnotationProcessor(libs.hilt.android.compiler)

    // Navigation
    implementation(libs.kotlin.serialization)
    implementation(libs.navigation)

    // Vosk
    implementation(libs.jna) { artifact { type = "aar" } }
    implementation(libs.vosk.android)
    
    // SherpaOnnx AAR (完整版 1.12.14)
    // 包含所有功能：ASR、TTS、VAD等
    implementation(files("libs/sherpa-onnx-1.12.14.aar"))
    
    // Hyundai IT API AAR (设备控制接口)
    implementation(files("libs/hyundaiit-api-v0.1-2025-10-14-16-release.aar"))
    
    // Gson - required by Hyundai IT API
    implementation(libs.gson)
    androidTestImplementation(libs.gson)
    
    // LiteRT / Tensorflow Lite
    implementation(libs.litert)
    
    // ONNX Runtime for HiNudge wake word - 与OpenwakewordforAndroid-main保持一致
    implementation("com.microsoft.onnxruntime:onnxruntime-android:1.19.2")

    // OkHttp
    implementation(platform(libs.okhttp.bom))
    implementation(libs.okhttp)

    // Image loading
    implementation(libs.coil.compose)
    implementation(libs.accompanist.drawablepainter)

    // Permission Flow https://github.com/PatilShreyas/permission-flow-android
    implementation(libs.permission.flow.android)
    implementation(libs.permission.flow.compose)

    // Miscellaneous
    implementation(libs.unbescape)
    implementation(libs.jsoup)

    // Used by skills
    implementation(libs.exp4j)

    // Testing
    testImplementation(libs.kotest.runner.junit5)
    testImplementation(libs.kotest.assertions.core)
    testImplementation(libs.kotest.property)
    androidTestImplementation(libs.test.runner)
    androidTestImplementation(libs.test.rules)
    androidTestImplementation(libs.test.ui.automator)
}

// this is required to avoid NoClassDefFoundError for ActivityInvoker during androidTest
// https://github.com/android/android-test/issues/2247#issuecomment-2194435444
configurations.configureEach {
    resolutionStrategy {
        force(libs.test.core)
        // 强制统一ONNX Runtime版本，避免版本冲突 - 与OpenwakewordforAndroid-main保持一致
        force("com.microsoft.onnxruntime:onnxruntime-android:1.19.2")
        force("ai.onnxruntime:onnxruntime:1.19.2")
    }
}

fun gitBranch(): String {
    return try {
        providers.exec {
            commandLine("git", "rev-parse", "--abbrev-ref", "HEAD")
        }.standardOutput.asText.get().trim()
    } catch (e: Exception) {
        logger.warn("Git isn't installed, using default name for debug app.")
        "debug"
    }
}
