package com.ai.voice.ui.home

import android.app.Application
import androidx.compose.material3.SnackbarHostState
import androidx.datastore.core.DataStore
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.Job
import kotlinx.coroutines.flow.filter
import kotlinx.coroutines.launch
import org.dicio.skill.context.SkillContext
import com.ai.voice.di.SkillContextInternal
import com.ai.voice.di.SpeechOutputDeviceWrapper
import com.ai.voice.di.SttInputDeviceWrapper
import com.ai.voice.di.WakeDeviceWrapper
import com.ai.voice.eval.SkillEvaluator
import com.ai.voice.eval.SkillHandler
import com.ai.voice.io.input.SttState
import com.ai.voice.io.speech.SnackbarSpeechDevice
import com.ai.voice.settings.datastore.UserSettings
import com.ai.voice.settings.datastore.WakeDevice
import com.ai.voice.settings.datastore.copy
import javax.inject.Inject

@HiltViewModel
class HomeScreenViewModel @Inject constructor(
    application: Application,
    val skillContext: SkillContextInternal,
    val skillHandler: SkillHandler,
    val dataStore: DataStore<UserSettings>,
    val sttInputDevice: SttInputDeviceWrapper,
    val speechOutputDevice: SpeechOutputDeviceWrapper,
    val wakeDevice: WakeDeviceWrapper,
    val skillEvaluator: SkillEvaluator,
    // this is always instantiated, but will do nothing if
    // it is not the speech device chosen by the user
    snackbarSpeechDevice: SnackbarSpeechDevice,
) : AndroidViewModel(application) {

    private var showSnackbarJob: Job? = null
    val snackbarHostState = SnackbarHostState()

    init {
        // show snackbars generated by the SnackbarSpeechDevice
        viewModelScope.launch {
            snackbarSpeechDevice.events.collect {
                if (it == null) {
                    // "stop speaking", i.e. remove the current snackbar
                    showSnackbarJob?.cancel()
                } else {
                    // replace the current snackbar
                    showSnackbarJob?.cancel()
                    showSnackbarJob = launch {
                        snackbarHostState.showSnackbar(it)
                    }
                }
            }
        }

        // stop speaking when the STT device starts listening
        viewModelScope.launch {
            sttInputDevice.uiState
                .filter { it == SttState.Listening }
                .collect { speechOutputDevice.stopSpeaking() }
        }
    }

    fun disableWakeWord() {
        viewModelScope.launch {
            dataStore.updateData {
                it.copy { wakeDevice = WakeDevice.WAKE_DEVICE_NOTHING }
            }
        }
    }
}
