#!/bin/bash

# 版本号更新脚本
# 在git commit后自动更新VERSION文件

# 获取git commit数量
GIT_COMMIT_COUNT=$(git rev-list --count HEAD 2>/dev/null || echo "0")

# 基础版本号配置
BASE_VERSION_MAJOR=3
BASE_VERSION_MINOR=3
BASE_VERSION_CODE=16

# 版本号计算规则：修订号0-99循环，每100次commit次版本号+1，次版本号超过99时主版本号+1
REVISION_NUMBER=$((GIT_COMMIT_COUNT % 100))  # 修订号：0-99循环
MINOR_VERSION_INCREMENT=$((GIT_COMMIT_COUNT / 100 % 100))  # 次版本号增量：0-99
MAJOR_VERSION_INCREMENT=$((GIT_COMMIT_COUNT / 10000))  # 主版本号增量

MINOR_VERSION=$((BASE_VERSION_MINOR + MINOR_VERSION_INCREMENT))
MAJOR_VERSION=$((BASE_VERSION_MAJOR + MAJOR_VERSION_INCREMENT))

# 最终版本号
FINAL_VERSION_CODE=$((BASE_VERSION_CODE + GIT_COMMIT_COUNT))
FINAL_VERSION_NAME="${MAJOR_VERSION}.${MINOR_VERSION}.${REVISION_NUMBER}"

# 更新VERSION文件
echo "$FINAL_VERSION_NAME" > VERSION

echo "✅ 版本号已更新: $FINAL_VERSION_NAME (versionCode: $FINAL_VERSION_CODE)"
echo "   Git commit count: $GIT_COMMIT_COUNT"

