name: Take screenshots and create Pull Request

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Setup Python dependencies for the screenshot server
        run: python -m pip install flask

      - name: Start screenshot server
        run: python ./app/src/androidTest/kotlin/org/stypox/dicio/screenshot/screenshot_server.py &

      - name: Run Android instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: default
          arch: x86_64
          profile: Nexus 5X
          script: ./gradlew connectedCheck -P android.testInstrumentationRunnerArguments.class=org.stypox.dicio.screenshot.ScreenshotTakerTest

      - name: Print git status
        run: git status

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: gh-action-update-screenshots
          commit-message: "Update screenshots"
